(() => {
"use strict";
const KEY="oracleLab.v1";
const base={xp:0,readings:[],journal:[],studied:[],followups:[],spreads:[],practice:[],quiz:0,memoryBest:null};
let state=JSON.parse(localStorage.getItem(KEY)||"null")||base;
const save=()=>localStorage.setItem(KEY,JSON.stringify(state));
const $=id=>document.getElementById(id);
const cards=window.tarotCards||[];
const group=c=>c.file.toLowerCase().startsWith("cups")?"Cups":c.file.toLowerCase().startsWith("pentacles")?"Pentacles":c.file.toLowerCase().startsWith("swords")?"Swords":c.file.toLowerCase().startsWith("wands")?"Wands":"Major Arcana";
const img=c=>"images/cards/"+c.file;
const cardByName=n=>cards.find(c=>c.name===n);
const esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));
const addXP=n=>{state.xp+=n;save();renderStats()};
function renderStats(){
 $("xp").textContent=state.xp;$("readingCount").textContent=state.readings.length;$("journalCount").textContent=state.journal.length;$("studyCount").textContent=state.studied.length;
 const level=Math.floor(state.xp/100)+1, into=state.xp%100;$("levelText").textContent="Level "+level+" • "+into+"/100 XP to the next level";$("xpBar").style.width=into+"%";
 const defs=[["🏅 First Steps",state.xp>=20],["📖 First Journal",state.journal.length>=1],["🎴 10 Cards Studied",state.studied.length>=10],["🧠 Quiz Explorer",state.quiz>=5],["🔥 7 Practice Days",state.practice.length>=7],["🗺 Major Arcana Explorer",state.studied.filter(n=>{const c=cardByName(n);return c&&group(c)==="Major Arcana"}).length>=22],["📚 50 Journal Entries",state.journal.length>=50],["✨ 100 XP",state.xp>=100]];
 $("achievements").innerHTML=defs.map(d=>'<span class="achievement '+(d[1]?"":"locked")+'">'+d[0]+"</span>").join("");
}
function initDaily(){
 const day=Math.floor(Date.now()/86400000),c=cards[day%cards.length];
 $("dailyCard").innerHTML='<div class="mini-card"><img src="'+img(c)+'" alt="'+esc(c.name)+'"><div><strong>'+esc(c.name)+'</strong><br><span class="tag">'+esc(group(c))+'</span></div></div><p>'+esc(c.upright)+'</p>';
 $("newDaily").onclick=()=>{const d=cards[Math.floor(Math.random()*cards.length)];$("dailyCard").innerHTML='<div class="mini-card"><img src="'+img(d)+'" alt="'+esc(d.name)+'"><div><strong>'+esc(d.name)+'</strong></div></div><p>'+esc(d.upright)+'</p>';addXP(2)};
}
function initChallenge(){
 const c=cards[Math.floor(new Date().getDate()*7)%cards.length];$("challengeText").innerHTML="<strong>"+esc(c.name)+"</strong> — "+esc(c.category)+"<br><span class='lab-note'>Keywords: "+esc(c.keywords.join(", "))+"</span>";
 $("challengeReveal").onclick=()=>{$("challengeResult").hidden=false;$("challengeResult").innerHTML="<strong>Reflection guide</strong><p>"+esc(c.upright)+"</p><p>Notice the imagery first. Then ask: how could this card's theme apply to the question without assuming a fixed outcome?</p>";addXP(10)};
}
const questions=[
["Which part of the deck contains 22 cards? ",["Major Arcana","Minor Arcana","Court cards"],0],
["Which suit is commonly associated with emotions and relationships? ",["Swords","Cups","Wands"],1],
["What is a useful first step in interpreting a card? ",["Check every prediction online","Describe what you notice","Ask the card for certainty"],1],
["What can a reversal be used for? ",["A guaranteed opposite meaning","An alternative or blocked expression of a theme","A prediction of a negative event"],1],
["Why keep a Tarot journal? ",["To prove predictions","To track reflection and learning over time","To replace evidence"],1],
["How many cards are in a traditional Tarot deck? ",["52","72","78"],2]
];
let qi=0;
function quiz(){const q=questions[qi%questions.length];$("quizQuestion").textContent=q[0];$("quizOptions").innerHTML=q[1].map((x,i)=>'<button class="lab-btn small" data-i="'+i+'">'+esc(x)+"</button>").join(" ");[...$("quizOptions").querySelectorAll("button")].forEach(b=>b.onclick=()=>{const ok=+b.dataset.i===q[2];$("quizResult").hidden=false;$("quizResult").textContent=ok?"Correct! +10 XP":"Not quite — review the explanation and try another question.";if(ok){state.quiz++;addXP(10)}else save();qi++})}
$("nextQuiz").onclick=quiz;
function comboInit(){const s=$("comboCards");cards.forEach((c,i)=>{const o=document.createElement("option");o.value=i;o.textContent=c.name;s.appendChild(o)});s.onchange=comboRender}
function comboRender(){const picked=[...$("comboCards").selectedOptions].map(o=>cards[+o.value]).slice(0,5);if(picked.length<2){$("comboResult").textContent="Choose at least two cards.";return}const suits=[...new Set(picked.map(group))];const keys=[...new Set(picked.flatMap(c=>c.keywords))];$("comboResult").innerHTML="<strong>"+picked.map(c=>esc(c.name)).join(" + ")+"</strong><p>Shared groups: "+suits.map(esc).join(", ")+"</p><p>Recurring themes: "+keys.slice(0,8).map(k=>'<span class="tag">'+esc(k)+"</span>").join(" ")+"</p><p>Read the cards as a conversation. Ask what the first card establishes, what the next card changes or adds, and where the themes agree or conflict.</p>";}
function oracle(){const f=$("oracleFocus").value,g=$("oracleGoal").value.trim()||"what I should notice";const sets={Relationships:["What is the current dynamic?","What am I bringing to this situation?","What could support clearer communication?"],Career:["What is the current situation?","What resource or skill can I use?","What deserves further consideration?"],"Decision making":["What do I already know?","What am I overlooking?","What is within my control?"],"Personal growth:["What pattern is asking for attention?","What strength can I draw on?","What small step supports growth?"],"General reflection:["What is most important to notice?","What perspective am I missing?","What can I reflect on next?" ]};const arr=sets[f]||sets["General reflection"];$("oracleResult").hidden=false;$("oracleResult").innerHTML="<strong>"+esc(f)+"</strong><p>Question: "+esc(g)+"</p><ol>"+arr.map(esc).map(x=>"<li>"+x+"</li>").join("")+"</ol><p>Suggested draw: one card per position. Record your first observations before consulting the card guide.</p>";addXP(5)}
$("oracleBuild").onclick=oracle;
let slotCount=0;
function addSlot(name){slotCount++;const row=document.createElement("div");row.className="slot-row";row.dataset.slot=slotCount;row.innerHTML='<input class="lab-input" placeholder="Position '+slotCount+' — e.g. Situation" value="'+esc(name||"")+'"><button type="button" class="lab-btn small remove-slot">×</button>';row.querySelector(".remove-slot").onclick=()=>{row.remove()};$("spreadSlots").appendChild(row)}
$("addSlot").onclick=()=>addSlot();addSlot("Situation");addSlot("Challenge");addSlot("Perspective");
function renderSpreads(){if(!state.spreads.length){$("savedSpreads").textContent="No saved spreads yet.";return}$("savedSpreads").innerHTML=state.spreads.map((s,i)=>'<div class="journal-entry"><strong>'+esc(s.name)+'</strong><div>'+s.positions.map(esc).join(" • ")+'</div><button class="lab-btn small" data-del="'+i+'">Delete</button></div>').join("");$("savedSpreads").querySelectorAll("[data-del]").forEach(b=>b.onclick=()=>{state.spreads.splice(+b.dataset.del,1);save();renderSpreads()})}
$("saveSpread").onclick=()=>{const positions=[...$("spreadSlots").querySelectorAll("input")].map(i=>i.value.trim()).filter(Boolean);if(!positions.length)return;state.spreads.push({name:$("spreadName").value.trim()||"My Tarot Spread",positions});addXP(15);renderSpreads()};
function renderJournal(){if(!state.journal.length){$("journalList").innerHTML='<p class="lab-note">No entries yet.</p>';return}$("journalList").innerHTML=state.journal.slice().reverse().slice(0,8).map((e,i)=>'<div class="journal-entry"><strong>'+esc(e.date)+'</strong><br><b>'+esc(e.question||"Untitled")+'</b><br>'+esc(e.cards)+'<p>'+esc(e.notes)+'</p></div>').join("")}
$("saveJournal").onclick=()=>{const notes=$("journalNotes").value.trim();if(!notes)return;state.journal.push({date:new Date().toLocaleDateString("en-GB"),question:$("journalQuestion").value,cards:$("journalCards").value,notes});addXP(20);$("journalQuestion").value="";$("journalCards").value="";$("journalNotes").value="";renderJournal()};
function renderFollow(){if(!state.followups.length){$("followList").innerHTML="";return}$("followList").innerHTML=state.followups.slice().reverse().slice(0,5).map(e=>'<div class="journal-entry"><strong>'+esc(e.date)+'</strong><br>'+esc(e.question)+'<p>'+esc(e.outcome)+'</p><span class="tag">'+esc(e.rating)+'</span></div>').join("")}
$("saveFollow").onclick=()=>{const q=$("followQuestion").value.trim(),o=$("followOutcome").value.trim();if(!q||!o)return;state.followups.push({date:new Date().toLocaleDateString("en-GB"),question:q,outcome:o,rating:$("followRating").value});addXP(15);$("followQuestion").value="";$("followOutcome").value="";renderFollow()};
function renderStatsLab(){const freq={};state.readings.flatMap(r=>r.cards||[]).concat(state.journal.flatMap(j=>(j.cards||"").split(","))).map(s=>s.trim()).filter(Boolean).forEach(n=>freq[n]=(freq[n]||0)+1);const top=Object.entries(freq).sort((a,b)=>b[1]-a[1]).slice(0,8);$("labStats").innerHTML="<p><b>Stored activity</b></p><table class='lab-table'><tr><th>Metric</th><th>Value</th></tr><tr><td>XP</td><td>"+state.xp+"</td></tr><tr><td>Follow-ups</td><td>"+state.followups.length+"</td></tr><tr><td>Saved spreads</td><td>"+state.spreads.length+"</td></tr><tr><td>Practice days</td><td>"+state.practice.length+"</td></tr></table>"+(top.length?"<p><b>Most recorded cards</b></p>"+top.map(x=>'<span class="tag">'+esc(x[0])+" ×"+x[1]+"</span>").join(" "):"")};
function journey(){const major=cards.filter(c=>group(c)==="Major Arcana");$("journeyPath").innerHTML=major.map(c=>'<button class="journey-node '+(state.studied.includes(c.name)?"done":"")+'" data-card="'+esc(c.name)+'">'+esc(c.name)+'</button>').join("");$("journeyPath").querySelectorAll("button").forEach(b=>b.onclick=()=>{const n=b.dataset.card;if(state.studied.includes(n))state.studied=state.studied.filter(x=>x!==n);else{state.studied.push(n);addXP(5)}save();journey();renderStats()})}
const practices=["Describe one card without interpreting it.","Study one Major Arcana card.","Study one Minor Arcana suit.","Try a one-card reading.","Write three better Tarot questions.","Study a court card.","Compare upright and reversed themes.","Record a reading before checking a guide.","Explore a card's symbols.","Try a three-card spread.","Review an old journal entry.","Write what is within your control.","Study a number from Ace to Ten.","Look for repeated themes across two cards.","Do a reading without asking for a prediction.","Reflect on a reading from someone else's perspective.","Study one card combination.","Notice your first emotional response to a card.","Re-read a past interpretation.","Take a day off and return with fresh eyes.","Create a personal spread.","Explore a card you usually overlook.","Compare two cards from the same suit.","Write a question without yes/no wording.","Record what actually happened after a reading.","Study a historical Tarot topic.","Review your reading boundaries.","Practise separating observation from interpretation.","Choose a card and write five questions about it.","Write what you learned this month."];
function practice(){ $("challengeList").innerHTML=practices.map((p,i)=>'<label class="lab-check"><input type="checkbox" data-practice="'+i+'" '+(state.practice.includes(i)?"checked":"")+'> Day '+(i+1)+": "+esc(p)+"</label>").join("");$("challengeList").querySelectorAll("input").forEach(c=>c.onchange=()=>{const i=+c.dataset.practice;if(c.checked&&!state.practice.includes(i)){state.practice.push(i);addXP(5)}else if(!c.checked)state.practice=state.practice.filter(x=>x!==i);save();renderStats()})}
let mem=[];
function memory(){const chosen=[...cards].sort(()=>Math.random()-.5).slice(0,6);mem=chosen.flatMap(c=>[{c,uid:Math.random()},{c,uid:Math.random()}]).sort(()=>Math.random()-.5);$("memoryGrid").innerHTML=mem.map((x,i)=>'<button class="memory-tile" data-i="'+i+'" aria-label="Hidden card">?</button>').join("");let first=null,lock=false,matches=0,moves=0;$("memoryStatus").textContent="";$("memoryGrid").querySelectorAll("button").forEach(b=>b.onclick=()=>{if(lock||b.classList.contains("matched"))return;const i=+b.dataset.i,x=mem[i];b.innerHTML='<img src="'+img(x.c)+'" alt="'+esc(x.c.name)+'">';if(first===null){first=i;return}moves++;if(mem[first].c.name===x.c.name){$("memoryGrid").querySelectorAll("button")[first].classList.add("matched");b.classList.add("matched");matches++;first=null;if(matches===6){$("memoryStatus").textContent="Complete in "+moves+" moves!";addXP(Math.max(5,50-moves))}}else{lock=true;setTimeout(()=>{$("memoryGrid").querySelectorAll("button")[first].textContent="?";b.textContent="?";first=null;lock=false},650)}})}
$("memoryStart").onclick=memory;
renderStats();initDaily();initChallenge();quiz();comboInit();renderSpreads();renderJournal();renderFollow();renderStatsLab();journey();practice();memory();
})();